import {finishVariants} from './finish-data.js?v=9e675244bed0';
export const profiles = [
  { bodyWidth:16, ledBase:1.1, mount:'surface', family:'Meblowe', application:'Niski profil pod szafkę', instruction:'assets/sources/micro-installation.pdf', id: 'micro', name: 'MICRO-PLUS', brand: 'KLUŚ', ref: 'A02966', width: 16, height: 6, channel: 11.2, model: 'assets/sources/micro-plus.3ds', geometry: 'Model producenta 3DS', source: 'assets/sources/micro-plus.pdf', covers: ['hs-opal', 'hs-clear', 'liger-black', "liger-opal", "kapro-opal", "kapro-clear"] },
  { bodyWidth:16.2, ledBase:1.1, mount:'surface', family:'Meblowe', application:'Głębszy kanał światła', instruction:'assets/sources/pds-installation.pdf', id: 'pds', name: 'PDS-4-PLUS', brand: 'KLUŚ', ref: 'A01263', width: 16.2, height: 12, channel: 14, geometry: 'Model uproszczony · wymiary z arkusza KLUŚ', source: 'assets/sources/pds-4-plus.pdf', covers: ['hs11-opal', 'hs11-clear', 'liger11-black', "liger11-satin", "kat11-opal", "kat11-clear", "lenso11"] },  {"id": "microk", "name": "MICRO-K", "brand": "KLUŚ", "ref": "MICRO-K-ALU-2M", "width": 22, "height": 6, "bodyWidth": 15.2, "channel": 11.2, "ledBase": 1.1, "mount": "recessed", "family": "Wpust", "application": "Półka z frezem · model archiwalny", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/micro-k-section.jpg", "instruction": "assets/sources/micro-k-section.jpg", "covers": ["hs-opal", "hs-clear", "liger-black"]},
  {"id": "piko", "name": "PIKO", "brand": "KLUŚ", "ref": "A08288", "width": 10, "height": 7, "bodyWidth": 10, "channel": 7, "ledBase": 2, "mount": "surface", "family": "Mini", "application": "Wąskie taśmy Slim", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/piko.pdf", "instruction": "assets/sources/piko-installation.pdf", "covers": ["piko-opal"]},
  {"id": "larko", "name": "LARKO", "brand": "KLUŚ", "ref": "A05552", "width": 46.2, "height": 24.5, "bodyWidth": 26.2, "channel": 24, "ledBase": 2, "mount": "recessed", "family": "Wpust", "application": "Osadzenie na sprężynach", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/larko.pdf", "instruction": "assets/sources/larko-installation.pdf", "covers": ["hs22-opal", "hs22-clear", "liger22-black", "liger22-satin", "g22r-satin", "g22r-clear", "g22r-black", "g22s-satin", "g22s-black"]},
  {"id": "kozus", "name": "KOZUS", "brand": "KLUŚ", "ref": "A07823", "width": 66.8, "height": 17.5, "bodyWidth": 26.8, "channel": 24, "ledBase": 4.8, "mount": "drywall", "family": "Regips", "application": "Linia światła pod szpachlę", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/kozus.pdf", "instruction": "assets/sources/kozus-installation.pdf", "covers": ["hs22-opal", "hs22-clear", "liger22-black", "liger22-satin", "g22r-satin", "g22r-clear", "g22r-black", "g22s-satin", "g22s-black"]},

  {"id": "pdszm", "name": "PDS-ZM-PLUS", "brand": "KLUŚ", "ref": "A02056", "width": 16.2, "height": 15, "bodyWidth": 16.2, "channel": 14, "ledBase": 5, "mount": "surface", "family": "Meblowe", "application": "Kanał montażowy ZM", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/pds-zm-plus.pdf", "instruction": "assets/sources/pds-zm-plus-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-pds-zm-plus-2369", "catalogStatus": "Available", "finishes": ["silver", "black", "white"], "covers": ["hs11-opal", "hs11-clear", "liger11-black", "liger11-satin", "kat11-opal", "kat11-clear", "lenso11"]},
  {"id": "alu45", "name": "45-ALU", "brand": "KLUŚ", "ref": "A04023", "width": 19, "height": 19, "bodyWidth": 19, "channel": 11.2, "ledBase": 7.2, "mount": "surface", "family": "Kątowe", "application": "Światło pod kątem 45°", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/45-alu.pdf", "instruction": "assets/sources/45-alu-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-45-alu-2351", "catalogStatus": "Available", "finishes": ["silver", "black", "white"], "covers": ["hs11-opal", "hs11-clear", "liger11-black", "liger11-satin", "kat11-opal", "kat11-clear", "lenso11"], "ledZ": -2.3, "ledAngle": 45, "coverY": 13.8, "coverZ": 4.3},
  {"id": "pikozm", "name": "PIKO-ZM", "brand": "KLUŚ", "ref": "A01168", "width": 10, "height": 9.7, "bodyWidth": 10, "channel": 7, "ledBase": 4.7, "mount": "surface", "family": "Mini", "application": "Miniatura z mocowaniem na klik", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/piko-zm.pdf", "instruction": "assets/sources/piko-zm-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-piko-zm-2381", "catalogStatus": "Available", "finishes": ["silver", "black", "white"], "covers": ["piko7-opal", "piko7-black"]},
  {"id": "pikoo", "name": "PIKO-O", "brand": "KLUŚ", "ref": "A01167", "width": 10.5, "height": 7, "bodyWidth": 10.5, "channel": 6, "ledBase": 2.5, "mount": "surface", "family": "Mini", "application": "Okrągły przekrój · osłona PIKO-7R", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/piko-o.pdf", "instruction": "assets/sources/piko-o-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-piko-o-2233", "catalogStatus": "Available", "finishes": ["silver", "black", "white"], "covers": ["piko7r-opal", "piko7r-clear", "piko7r-black"]},
  {"id": "giza", "name": "GIZA", "brand": "KLUŚ", "ref": "A05556", "width": 26.2, "height": 9.5, "bodyWidth": 26.2, "channel": 22, "ledBase": 4.5, "mount": "surface", "family": "Szerokie", "application": "Niski profil z szeroką linią", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/giza.pdf", "instruction": "assets/sources/giza-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-giza-2356", "catalogStatus": "Available", "finishes": ["silver", "black", "white"], "covers": ["hs22-opal", "hs22-clear", "liger22-black", "liger22-satin", "g22r-satin", "g22r-clear", "g22r-black", "g22s-satin", "g22s-black"]},
  {"id": "lipod", "name": "LIPOD", "brand": "KLUŚ", "ref": "A05554", "width": 26.2, "height": 24.5, "bodyWidth": 26.2, "channel": 24, "ledBase": 4.5, "mount": "surface", "family": "Szerokie", "application": "Głęboki kanał · łączenie w system", "geometry": "Przekrój odtworzony z karty KLUŚ", "source": "assets/sources/lipod.pdf", "instruction": "assets/sources/lipod-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-lipod-2424", "catalogStatus": "Available", "finishes": ["silver", "black", "white"], "covers": ["hs22-opal", "hs22-clear", "liger22-black", "liger22-satin", "g22r-satin", "g22r-clear", "g22r-black", "g22s-satin", "g22s-black"]},
  {"id": "microh", "name": "MICRO-H", "brand": "KLUŚ", "ref": "A00599", "width": 16.0, "height": 8.7, "bodyWidth": 16, "channel": 11.2, "ledBase": 3.9, "mount": "surface", "family": "Meblowe", "application": "Ukryty mocownik H", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/micro-h.pdf", "instruction": "assets/sources/micro-h-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-micro-h-2211", "finishes": ["silver"], "covers": ["hs-opal", "hs-clear", "liger-black", "liger-opal", "kapro-opal", "kapro-clear"], "universal": true, "catalogEdition": "2026-09-01"},
  {"id": "pdsh", "name": "PDS-H", "brand": "KLUŚ", "ref": "A09204", "width": 16.0, "height": 16.0, "bodyWidth": 16, "channel": 14.0, "ledBase": 3.9, "mount": "surface", "family": "Meblowe", "application": "Kanał H · mocowanie na klik", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/pds-h.pdf", "instruction": "assets/sources/pds-h-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-pds-h-2430", "finishes": ["silver"], "covers": ["hs11-opal", "hs11-clear", "liger11-black", "ka11-opal", "ka11-clear", "liger11-satin", "kat11-opal", "kat11-clear", "lenso11"], "universal": true, "catalogEdition": "2026-09-01"},
  {"id": "siler", "name": "SILER", "brand": "KLUŚ", "ref": "A09325", "width": 19.0, "height": 12.0, "bodyWidth": 19, "channel": 16.0, "ledBase": 1.2, "mount": "surface", "family": "Szerokie", "application": "Linia 16 mm · osłona LIGER-16", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/siler.pdf", "instruction": "assets/sources/siler-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-siler-2238", "finishes": ["silver", "black", "white"], "covers": ["liger16-opal", "liger16-clear"], "universal": true, "catalogEdition": "2026-09-01"},
  {"id": "micronk", "name": "MICRO-NK", "brand": "KLUŚ", "ref": "A01587", "width": 22.2, "height": 6.0, "bodyWidth": 15.2, "channel": 11.2, "ledBase": 1.1, "mount": "recessed", "family": "Wpust", "application": "Niski wpust z kołnierzem", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/micro-nk.pdf", "instruction": "assets/sources/micro-nk-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-micro-nk-2214", "finishes": ["silver", "black", "white"], "covers": ["hs11-opal", "hs11-clear", "liger11-black", "ka11-opal", "ka11-clear", "liger11-satin", "kat11-opal", "kat11-clear"], "universal": true, "catalogEdition": "2026-09-01", "seatDepth": 5.0},
  {"id": "pdsnk", "name": "PDS-NK", "brand": "KLUŚ", "ref": "A01588", "width": 22.2, "height": 12.0, "bodyWidth": 16.2, "channel": 14.0, "ledBase": 1.1, "mount": "recessed", "family": "Wpust", "application": "Głębszy wpust z kołnierzem", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/pds-nk.pdf", "instruction": "assets/sources/pds-nk-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-pds-nk-2322", "finishes": ["silver", "black", "white"], "covers": ["hs11-opal", "hs11-clear", "liger11-black", "ka11-opal", "ka11-clear", "liger11-satin", "kat11-opal", "kat11-clear", "lenso11"], "universal": true, "catalogEdition": "2026-09-01", "seatDepth": 11.0},
  {"id": "plus45", "name": "45-PLUS", "brand": "KLUŚ", "ref": "A00005", "width": 19, "height": 19, "bodyWidth": 19, "channel": 8.5, "ledBase": 5.79, "mount": "surface", "family": "Kątowe", "application": "Kanał pod kątem 45°", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/45-plus.pdf", "instruction": "assets/sources/45-plus-installation.pdf", "finishes": ["silver", "black", "white"], "covers": ["hs11-opal", "hs11-clear", "liger11-black", "ka11-opal", "ka11-clear", "liger11-satin", "kat11-opal", "kat11-clear", "ka11r-opal"], "universal": true, "catalogEdition": "2026-09-01", "ledZ": -3.21, "ledAngle": 45, "coverY": 13.5, "coverZ": 4, "channelDepth": 11.6},
  {"id": "alu4516", "name": "45-16", "brand": "KLUŚ", "ref": "A08504", "width": 16.0, "height": 16.0, "bodyWidth": 16, "channel": 11.2, "ledBase": 5.45, "mount": "surface", "family": "Kątowe", "application": "Narożnik 16 × 16 mm", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/45-16.pdf", "instruction": "assets/sources/45-16-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-45-16-2350", "finishes": ["silver"], "covers": ["hs11-opal", "hs11-clear", "liger11-black", "ka11-opal", "ka11-clear", "liger11-satin", "kat11-opal", "kat11-clear", "lenso11"], "universal": true, "catalogEdition": "2026-09-01", "ledZ": -1.95, "ledAngle": 45, "coverY": 11.5, "coverZ": 3.5, "channelDepth": 8.5},
  {"id": "tami", "name": "TAMI", "brand": "KLUŚ", "ref": "A05390", "width": 15.9, "height": 7.0, "bodyWidth": 15.9, "channel": 13.0, "ledBase": 1.1, "mount": "surface", "family": "Meblowe", "application": "Niski profil · osłona T-13", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/tami.pdf", "instruction": "assets/sources/tami-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-tami-2243", "finishes": ["silver"], "covers": ["t13-clear"], "universal": true, "catalogEdition": "2026-09-01"},
  {"id": "tako", "name": "TAKO", "brand": "KLUŚ", "ref": "A05392", "width": 27.2, "height": 9.1, "bodyWidth": 15.9, "channel": 13.0, "ledBase": 3.5, "mount": "recessed", "family": "Wpust", "application": "Wpust z łagodnym kołnierzem", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/tako.pdf", "instruction": "assets/sources/tako-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-tako-2242", "finishes": ["silver"], "covers": ["t13-clear"], "universal": true, "catalogEdition": "2026-09-01", "seatDepth": 8.2},
  {"id": "tost", "name": "TOST", "brand": "KLUŚ", "ref": "A05393", "width": 25.9, "height": 9.1, "bodyWidth": 25.9, "channel": 13.0, "ledBase": 4.5, "mount": "surface", "family": "Meblowe", "application": "Zaokrąglone boki · mocowanie do płyty", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/tost.pdf", "instruction": "assets/sources/tost-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-tost-2246", "finishes": ["silver"], "covers": ["t13-clear"], "universal": true, "catalogEdition": "2026-09-01"},
  {"id": "pac", "name": "PAC-ALU", "brand": "KLUŚ", "ref": "A04370", "width": 30.4, "height": 10.5, "bodyWidth": 30.4, "channel": 13.1, "ledBase": 4.8, "mount": "surface", "family": "Meblowe", "application": "Szersze skrzydełka montażowe", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/pac-alu.pdf", "instruction": "assets/sources/pac-alu-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-pac-alu-2413", "finishes": ["silver"], "covers": ["hs12-opal", "hs12-clear", "ka13-opal", "ka13-clear"], "universal": true, "catalogEdition": "2026-09-01"},
  {"id": "stos", "name": "STOS-ALU", "brand": "KLUŚ", "ref": "A04369", "width": 31.0, "height": 7.0, "bodyWidth": 31, "channel": 13.1, "ledBase": 2.1, "mount": "surface", "family": "Meblowe", "application": "Niski korpus z bocznymi skrzydełkami", "geometry": "Przekrój odtworzony z rysunku KLUŚ", "source": "assets/sources/stos-alu.pdf", "instruction": "assets/sources/stos-alu-installation.pdf", "url": "https://klusdesign.pl/produkt/profil-stos-alu-2240", "finishes": ["silver"], "covers": ["hs12-opal", "hs12-clear", "ka13-opal", "ka13-clear"], "universal": true, "catalogEdition": "2026-09-01"},
];
export const strips = [
  {"id": "premium-rgbw", "name": "Premium RGBW + 3000 K", "ref": "24E033-100-RGBWW50", "type": "RGBW", "package": "5050", "width": 10, "watts": 19.6, "lumens": 1400, "voltage": 24, "cct": 3000, "cri": 80, "density": 60, "cut": 100, "copperOz": 3, "source": "assets/sources/premium-rgbw.pdf", "markings": ["W", "R", "G", "B", "+24V"], "whiteWatts": 4.6, "whiteLumens": 500, "powerNote": "19,6 W/m według karty PDF; strona podaje 19,7 W/m. CRI dotyczy bieli."},
  { id: 'threeinone', name: 'Delux 3in1', ref: '24D160-11-3080-1010', type: '3IN1', width: 10, watts: 11, lumens: 1750, voltage: 24, cct: 3000, cri: 80, density: 160, cut: 50, source: 'assets/sources/delux-3in1.pdf', markings: ['+24V','−L','−M','−H'], modes: {low: {watts:3,lumens:460,terminal:'−L'},medium: {watts:6,lumens:930,terminal:'−M'},high: {watts:11,lumens:1750,terminal:'−H'}} },
  { id: 'cct', name: 'Premium CCT 2w1', ref: '24E024-100-10-CCT', type: 'CCT', width: 10, watts: 14.4, lumens: 1000, voltage: 24, cct: 3000, cctMin: 3000, cctMax: 6500, cri: 80, density: 60, cut: 100, source: 'https://www.prescot.pl/wp-content/uploads/2021/12/PRESCOT-LED-STRIP-LIGHTS-CATALOG-PREMIUM.pdf', markings: ['+24V','CW','WW'] },
  { id: 'delux', copperOz: 4, name: 'Delux CRI97', ref: '24D160-10-3097-810', type: 'SMD', width: 8, watts: 10, lumens: 1000, voltage: 24, cct: 3000, cri: 97, density: 160, cut: 50, source: 'https://www.prescot.com.pl/pl/p/Tasma-LED-Delux-24V-160ledm-SMD2835-10Wm-3000K-IP20-1000lmm-8mm-CRI97-PL7Y-10m/13516' },
  { id: 'cob', copperOz: 3, name: 'Premium COB LB', ref: '24EC384-042-8-WWL', type: 'COB', width: 8, watts: 4, lumens: 350, voltage: 24, cct: 3000, cri: 90, density: 384, cut: 50, source: 'https://www.prescot.com.pl/pl/c/Tasmy-LED-COB/579/2' },
  { id: 'slim', copperOz: 4, name: 'Delux Slim 4 mm', ref: '24DS004-050-4-WW', type: 'SMD', width: 4, watts: 6.8, lumens: 1100, voltage: 24, cct: 3000, cri: 80, density: 160, cut: 50, source: 'assets/sources/strip-records.json' },  {"id": "sshape", "name": "Premium S-shape 3000 K", "ref": "EF018-050-6-WW", "type": "SMD", "shape": "s", "package": "2835", "width": 6, "watts": 10.8, "lumens": 920, "voltage": 12, "cct": 3000, "cri": 80, "density": 60, "cut": 50, "source": "assets/sources/premium-catalog.pdf#page=16", "markings": ["+12V", "−"], "family": "S-shape"},
  {"id": "sshape-nw", "name": "Premium S-shape 4000 K", "ref": "EF018-050-6-NW", "type": "SMD", "shape": "s", "package": "2835", "width": 6, "watts": 10.8, "lumens": 1000, "voltage": 12, "cct": 4000, "cri": 80, "density": 60, "cut": 50, "source": "assets/sources/premium-catalog.pdf#page=16", "markings": ["+12V", "−"], "family": "S-shape"},
  {"id": "sshape-cw", "name": "Premium S-shape 6500 K", "ref": "EF018-050-6-W", "type": "SMD", "shape": "s", "package": "2835", "width": 6, "watts": 10.8, "lumens": 1030, "voltage": 12, "cct": 6500, "cri": 80, "density": 60, "cut": 50, "source": "assets/sources/premium-catalog.pdf#page=16", "markings": ["+12V", "−"], "family": "S-shape"},
  {"id": "slim5", "copperOz": 3, "name": "Premium Slim 5 mm", "ref": "24ES004-031-5-NW", "type": "SMD", "package": "2216", "width": 5, "watts": 9, "lumens": 720, "voltage": 24, "cct": 4000, "cri": 80, "density": 224, "cut": 31, "source": "assets/sources/premium-catalog.pdf#page=15", "family": "Slim"},
  {"id": "premium-slim4", "copperOz": 3, "name": "Premium Slim 4 mm", "ref": "24ES004-050-4-NW", "type": "SMD", "package": "2216", "width": 4, "watts": 5.6, "lumens": 430, "voltage": 24, "cct": 4000, "cri": 80, "density": 140, "cut": 50, "source": "assets/sources/premium-catalog.pdf#page=15", "family": "Slim"},

  {"id": "wcob", "name": "Premium WCOB 3000 K", "ref": "24WCOB320WW5IP62", "type": "COB", "technology": "WCOB", "width": 8, "watts": 10, "lumens": 1400, "voltage": 24, "cct": 3000, "cri": 90, "density": 320, "cut": 25, "source": "assets/sources/wcob-mono.pdf", "ip": "IP62", "encapsulation": "coating", "envelopeVerified": true, "image": "assets/sources/reference-19377-0.png", "envelopeWidth": 8, "envelopeHeight": 5, "cutVerified": true},
  {"id": "wcob-nw", "name": "Premium WCOB 4000 K", "ref": "24WCOB320NW5IP62", "type": "COB", "technology": "WCOB", "width": 8, "watts": 10, "lumens": 1450, "voltage": 24, "cct": 4000, "cri": 90, "density": 320, "cut": 25, "source": "assets/sources/wcob-mono.pdf", "ip": "IP62", "encapsulation": "coating", "envelopeVerified": true, "image": "assets/sources/reference-19377-0.png", "envelopeWidth": 8, "envelopeHeight": 5, "cutVerified": true},
  {"id": "wcob-cw", "name": "Premium WCOB 6000 K", "ref": "24WCOB320W5IP62", "type": "COB", "technology": "WCOB", "width": 8, "watts": 10, "lumens": 1350, "voltage": 24, "cct": 6000, "cri": 90, "density": 320, "cut": 25, "source": "assets/sources/wcob-mono.pdf", "ip": "IP62", "encapsulation": "coating", "envelopeVerified": true, "image": "assets/sources/reference-19377-0.png", "envelopeWidth": 8, "envelopeHeight": 5, "cutVerified": true},
  {"id": "wcob-cct", "name": "Premium WCOB CCT", "ref": "24WCOB280CCT5IP62", "type": "CCT", "technology": "WCOB", "width": 8, "watts": 17, "lumens": 1300, "voltage": 24, "cct": 3000, "cri": 90, "density": 280, "cut": 25, "source": "assets/sources/wcob-cct.pdf", "ip": "IP62", "encapsulation": "coating", "envelopeVerified": true, "image": "assets/sources/reference-19380-0.jpg", "cutVerified": true, "cctMin": 2600, "cctMax": 6000, "markings": ["+24V", "CW", "WW"], "envelopeWidth": 8, "envelopeHeight": 5},
  {"id": "cob-ip67", "name": "Premium COB IP67 3000 K", "ref": "24EC320WW1IP67", "type": "COB", "technology": "COB", "width": 10, "watts": 10, "lumens": 700, "voltage": 24, "cct": 3000, "cri": 90, "density": 320, "cut": 50, "source": "https://prescot.com.pl/pl/p/Tasma-LED-Premium-24V-320ledm-COB-10Wm-3000K-IP67-700lmm-10mm-CRI90-3Y-1m/19273", "ip": "IP67", "encapsulation": "tube", "image": "assets/sources/reference-19273-0.jpg", "cutVerified": false, "cutNote": "Moduł 50 mm w podglądzie; potwierdź oznaczenia cięcia na rolce.", "envelopeVerified": false},
  {"id": "cob-ip67-nw", "name": "Premium COB IP67 4000 K", "ref": "24EC320NW1IP67", "type": "COB", "technology": "COB", "width": 10, "watts": 10, "lumens": 700, "voltage": 24, "cct": 4000, "cri": 90, "density": 320, "cut": 50, "source": "https://prescot.com.pl/pl/p/Tasma-LED-Premium-24V-320ledm-COB-10Wm-4000K-IP67-700lmm-10mm-CRI90-3Y-1m/19272", "ip": "IP67", "encapsulation": "tube", "image": "assets/sources/reference-19273-0.jpg", "cutVerified": false, "cutNote": "Moduł 50 mm w podglądzie; potwierdź oznaczenia cięcia na rolce.", "envelopeVerified": false},
];
export const covers = [
  { id: 'hs11-opal', name: 'HS-11 mleczna', ref: 'B17208F', transmission: .59, color: '#f3f0df' },
  { id: 'hs11-clear', name: 'HS-11 przezroczysta', ref: 'B17208C', transmission: .88, color: '#e6ecee' },
  { id: 'liger11-black', name: 'LIGER-11 czarna', ref: 'B17037B', transmission: .21, color: '#292a2b' },
  { id: 'hs-opal', name: 'HS mleczna', ref: 'B17208M', transmission: .73, color: '#f3f0df' },
  { id: 'hs-clear', name: 'HS przezroczysta', ref: 'B17208T', transmission: .94, color: '#e6ecee' },
  { id: 'liger-black', name: 'LIGER czarna', ref: 'B17037C', transmission: .32, color: '#292a2b' },  {"id": "piko-opal", "name": "PIKO-7 satynowa", "ref": "B17034S", "transmission": 0.43, "color": "#f3f0df", "width": 7},
  {"id": "hs22-opal", "name": "HS-22 mleczna", "ref": "B17011F", "transmission": 0.65, "color": "#f3f0df", "width": 22},
  {"id": "hs22-clear", "name": "HS-22 przezroczysta", "ref": "B17011C", "transmission": 0.88, "color": "#e6ecee", "width": 22},
  {"id": "liger22-black", "name": "LIGER-22 czarna", "ref": "B17032B", "transmission": 0.22, "color": "#292a2b", "width": 22},

  {"id": "piko7-opal", "name": "PIKO-7 satynowa · nowa", "ref": "B17001S", "width": 7, "transmission": 0.43, "color": "#f3f0df"},
  {"id": "piko7-black", "name": "PIKO-7 czarna", "ref": "B17001B", "width": 7, "transmission": 0.17, "color": "#292a2b"},
  {"id": "piko7r-opal", "name": "PIKO-7R satynowa", "ref": "B17164S", "width": 7.2, "transmission": 0.52, "color": "#f3f0df", "shape": "round"},
  {"id": "piko7r-clear", "name": "PIKO-7R transparentna", "ref": "B17164T", "width": 7.2, "transmission": 0.93, "color": "#e6ecee", "shape": "round"},
  {"id": "piko7r-black", "name": "PIKO-7R czarna", "ref": "B17164B", "width": 7.2, "transmission": 0.24, "color": "#292a2b", "shape": "round"},
  {"id": "ka11-opal", "name": "KA-11 mleczna", "ref": "B17064F", "width": 13.8, "transmission": 0.67, "color": "#eef0ec"},
  {"id": "ka11-clear", "name": "KA-11 przezroczysta", "ref": "B17064C", "width": 13.8, "transmission": 0.89, "color": "#eef0ec"},
  {"id": "liger16-opal", "name": "LIGER-16 satynowa", "ref": "B17039S", "width": 16, "transmission": 0.66, "color": "#eef0ec"},
  {"id": "liger16-clear", "name": "LIGER-16 przezroczysta", "ref": "B17039C", "width": 16, "transmission": 0.92, "color": "#eef0ec"},
  {"id": "t13-clear", "name": "T-13 półprzezroczysta", "ref": "B17015T", "width": 13, "transmission": 0.85, "color": "#eef0ec", "shape": "shallow"},
  {"id": "hs12-opal", "name": "HS-12 mleczna", "ref": "B17201M", "width": 13.2, "transmission": 0.73, "color": "#eef0ec"},
  {"id": "hs12-clear", "name": "HS-12 przezroczysta", "ref": "B17201T", "width": 13.2, "transmission": 0.94, "color": "#eef0ec"},
  {"id": "ka13-opal", "name": "KA-13 mleczna", "ref": "B17066F", "width": 13.2, "transmission": 0.72, "color": "#eef0ec"},
  {"id": "ka13-clear", "name": "KA-13 przezroczysta", "ref": "B17066C", "width": 13.2, "transmission": 0.91, "color": "#eef0ec"},
  {"id": "liger-opal", "name": "LIGER mleczna", "ref": "B17037M", "transmission": 0.7, "width": 12.4, "shape": "flat", "color": "#f2f0e8", "source": "assets/sources/micro-plus.pdf", "material": "PC"},
  {"id": "kapro-opal", "name": "KA-PRO mleczna", "ref": "B17064M", "transmission": 0.67, "width": 13.8, "shape": "flat", "color": "#f2f0e8", "source": "assets/sources/micro-plus.pdf", "material": "PC"},
  {"id": "kapro-clear", "name": "KA-PRO przezroczysta", "ref": "B17064T", "transmission": 0.94, "width": 13.8, "shape": "flat", "color": "#f2f0e8", "source": "assets/sources/micro-plus.pdf", "material": "PC"},
  {"id": "liger11-satin", "name": "LIGER-11 satyna", "ref": "B17037S", "transmission": 0.59, "width": 12.4, "shape": "flat", "color": "#f2f0e8", "source": "assets/sources/cover-b17037s.pdf", "material": "PC"},
  {"id": "kat11-opal", "name": "KA-T-11 mleczna", "ref": "B17179F", "transmission": 0.54, "width": 12.4, "shape": "flat", "color": "#f2f0e8", "source": "assets/sources/cover-b17179f.pdf", "material": "PVC", "maxWatts": 7},
  {"id": "kat11-clear", "name": "KA-T-11 przezroczysta", "ref": "B17179C", "transmission": 0.86, "width": 12.4, "shape": "flat", "color": "#f2f0e8", "source": "assets/sources/cover-b17179c.pdf", "material": "PVC", "maxWatts": 7},
  {"id": "lenso11", "name": "LENSO-11 · soczewka 30°", "ref": "B17112T", "transmission": 0.8, "width": 12, "shape": "lens", "color": "#f2f0e8", "source": "assets/sources/cover-b17112t.pdf", "material": "PC", "rise": 3.8, "lipDepth": 4, "beamAngle": 30, "capNote": "Podwyższona osłona wymaga osobnego doboru zamknięcia jej końców."},
  {"id": "ka11r-opal", "name": "KA-11R mleczna", "ref": "B17076F", "transmission": 0.62, "width": 13, "shape": "arch", "color": "#f2f0e8", "source": "assets/sources/cover-b17076f.pdf", "material": "PC", "rise": 2.9, "lipDepth": 4.1, "capNote": "Podwyższona osłona wymaga osobnego doboru zamknięcia jej końców."},
  {"id": "liger22-satin", "name": "LIGER-22 satyna", "ref": "B17032S", "transmission": 0.7, "width": 21.8, "shape": "flat", "color": "#f2f0e8", "source": "assets/sources/cover-b17032s.pdf", "material": "PC"},
  {"id": "g22r-satin", "name": "G-22R satyna", "ref": "B17006S", "transmission": 0.71, "width": 24.3, "shape": "dome", "color": "#f2f0e8", "source": "assets/sources/cover-b17006c.pdf", "material": "PMMA", "rise": 16.5, "lipDepth": 4, "capNote": "Podwyższona osłona wymaga osobnego doboru zamknięcia jej końców."},
  {"id": "g22r-clear", "name": "G-22R przezroczysta", "ref": "B17006C", "transmission": 0.94, "width": 24.3, "shape": "dome", "color": "#f2f0e8", "source": "assets/sources/cover-b17006c.pdf", "material": "PMMA", "rise": 16.5, "lipDepth": 4, "capNote": "Podwyższona osłona wymaga osobnego doboru zamknięcia jej końców."},
  {"id": "g22r-black", "name": "G-22R czarna", "ref": "B17006B", "transmission": 0.2, "width": 24.3, "shape": "dome", "color": "#292b2c", "source": "assets/sources/cover-b17006c.pdf", "material": "PMMA", "rise": 16.5, "lipDepth": 4, "capNote": "Podwyższona osłona wymaga osobnego doboru zamknięcia jej końców."},
  {"id": "g22s-satin", "name": "G-22S satyna", "ref": "B17013S", "transmission": 0.86, "width": 24, "shape": "square", "color": "#f2f0e8", "source": "assets/sources/cover-b17013s.pdf", "material": "PMMA", "rise": 16.5, "lipDepth": 4, "capNote": "Podwyższona osłona wymaga osobnego doboru zamknięcia jej końców."},
  {"id": "g22s-black", "name": "G-22S czarna", "ref": "B17013B", "transmission": 0.15, "width": 24, "shape": "square", "color": "#292b2c", "source": "assets/sources/cover-b17013s.pdf", "material": "PMMA", "rise": 16.5, "lipDepth": 4, "capNote": "Podwyższona osłona wymaga osobnego doboru zamknięcia jej końców."},
];
export const sleeves = [
  {id:'basic8',name:'PRO BASIC 8',ref:'KS-PRO-B-8',width:11,height:5,pcbMax:8,shape:'basic',clear:true,verified:true,source:'assets/sources/reference-13133-0.jpg',url:'https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-PRO-BASIC-8mm-TR/13133'},
  {id:'basic10',name:'PRO BASIC 10',ref:'KS-PRO-B-10',width:13,height:5,pcbMax:10,shape:'basic',clear:true,verified:true,source:'assets/sources/reference-13134-0.jpg',url:'https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-PRO-BASIC-10mm-TR/13134'},
  {id:'standard',name:'PRO STANDARD 14',ref:'KS-PRO-S-14',width:14,height:14,pcbMax:10,shape:'standard',verified:false,source:'assets/sources/reference-13135-0.jpg',url:'https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-PRO-STANDARD-14mm-ML/13135'},
  {id:'top',name:'PRO TOP 15 × 13',ref:'KS-PRO-TOP-15',width:15,height:13,pcbMax:10,shape:'top',verified:false,source:'assets/sources/reference-13137-0.jpg',url:'https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-PRO-TOP-15x13mm-ML/13137'},
  {"id": "clear8", "name": "Przezroczysta 8 mm", "ref": "KS-8MM", "width": 10, "height": 3.5, "pcbMax": 8, "shape": "basic", "clear": true, "verified": true, "source": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-przezroczysta-8mm/7491", "url": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-przezroczysta-8mm/7491", "family": "Standard", "pcbLift": 0.6},
  {"id": "clear10", "name": "Przezroczysta 10 mm", "ref": "KS-10MM", "width": 13, "height": 4, "pcbMax": 10, "shape": "basic", "clear": true, "verified": true, "source": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-przezroczysta-10mm/7490", "url": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-przezroczysta-10mm/7490", "family": "Standard", "pcbLift": 0.6},
  {"id": "clear12", "name": "Przezroczysta 12 mm", "ref": "KS-12MM", "width": 14.5, "height": 4, "pcbMax": 12, "shape": "basic", "clear": true, "verified": true, "source": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-przezroczysta-12mm/11626", "url": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-przezroczysta-12mm/11626", "family": "Standard", "pcbLift": 0.6},
  {"id": "milk8", "name": "Mleczna 8 mm", "ref": "KSM-8MM", "width": 10, "height": 3.5, "pcbMax": 8, "shape": "basic", "clear": false, "verified": true, "source": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-mleczna-8mm/7495", "url": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-mleczna-8mm/7495", "family": "Standard", "pcbLift": 0.6},
  {"id": "milk10", "name": "Mleczna 10 mm", "ref": "KSM-10MM", "width": 13, "height": 4, "pcbMax": 10, "shape": "basic", "clear": false, "verified": true, "source": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-mleczna-10mm/7494", "url": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-mleczna-10mm/7494", "family": "Standard", "pcbLift": 0.6},
  {"id": "side", "name": "PRO SLIM SIDE 4", "ref": "KS-PRO-SS-4", "width": 4, "height": 10, "pcbMax": 6, "shape": "side", "clear": false, "verified": false, "source": "assets/sources/reference-13136-0.jpg", "url": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-PRO-SLIM-SIDE-4mm-ML/13136", "family": "PRO", "pcbLift": 0, "pcbOrientation": "vertical", "fitNote": "Gabaryt 4 × 10 mm z rysunku. PCB w pionie; granica 6 mm w podglądzie wymaga potwierdzenia."},
  {"id": "oval", "name": "PRO OVAL 20", "ref": "KS-PRO-OVAL-20", "width": 20, "height": 20, "pcbMax": 10, "shape": "oval", "clear": false, "verified": false, "source": "assets/sources/reference-13138-0.jpg", "url": "https://prescot.com.pl/pl/p/Koszulka-silikonowa-do-tasm-LED-PRO-OVAL-20mm-ML/13138", "family": "PRO", "pcbLift": 2.2, "fitNote": "Średnica 20 mm i wejście 11 mm z rysunku; wysokość wewnętrzna do potwierdzenia."},
];
export function finishesFor(p){return Object.keys(finishVariants[p.ref]||{silver:{}});}
export function finishFor(p,value){return finishVariants[p.ref]?.[value]||{name:'Srebrny · wariant archiwalny',ref:p.ref,source:p.source};}
export function displayLength(s){return s.view==='zone'?300:s.view==='assembly'&&s.productScale==='length'&&!['end','entry'].includes(s.assemblyAngle)?Math.min(s.length,1000):100;}
export const defaults = {profile:'micro',strip:'delux',cover:'hs-opal',length:1000,finish:'silver',material:'white',mounting:'surface',view:'assembly',exploded:100,dimmer:65,cct:3000,light:true,repeat:50,print:'brand',powerMode:'high',detail:'segment',assemblyAngle:'perspective',zone:'under',zoneDetail:false,zoneOpen:true,showCable:false,mountStep:0,sleeve:'none',endcaps:false,showFixings:false,sealClosed:false,zonePosition:'front',zoneTrigger:'manual',lightStudy:false,productScale:'detail',backing:'200mp',rgbMode:'white',rgbColor:'#ff6424'};
export function normalize(raw = {}) {
  const s={...defaults};
  const choices={backing:['factory','200mp','300lse'],rgbMode:['white','rgb','mixed'],profile:profiles.map(p=>p.id),strip:strips.map(t=>t.id),cover:covers.map(c=>c.id),finish:['silver','black','white','raw'],material:['oak','walnut','white','graphite','sand'],mounting:['surface','recessed'],view:['assembly','installation','section','mounting','macro','zone'],assemblyAngle:['perspective','side','end','entry'],zonePosition:['front','back','shelf'],zoneTrigger:['manual','door'],detail:['segment','wiring','curve','sleeve','seal'],sleeve:['none',...sleeves.map(x=>x.id)],print:['brand','concept'],powerMode:['low','medium','high'],zone:['under','cabinet','drawer','drywall','shelf','plinth'],productScale:['detail','length']};
  for(const [key,values] of Object.entries(choices))if(values.includes(raw[key]))s[key]=raw[key];
  for(const [key,min,max] of [['length',100,3000],['exploded',0,100],['dimmer',0,100],['cct',2600,6500],['repeat',5,1000],['mountStep',0,4]])if(typeof raw[key]==='number'&&Number.isFinite(raw[key]))s[key]=Math.max(min,Math.min(max,raw[key]));
  if(typeof raw.rgbColor==='string'&&/^#[0-9a-f]{6}$/i.test(raw.rgbColor))s.rgbColor=raw.rgbColor;
  s.mountStep=Math.round(s.mountStep);
  for(const key of ['light','lightStudy','zoneDetail','zoneOpen','showCable','endcaps','showFixings','sealClosed'])if(typeof raw[key]==='boolean')s[key]=raw[key];
  const p=profiles.find(p=>p.id===s.profile),t=strips.find(t=>t.id===s.strip);
  if(!p.covers.includes(s.cover))s.cover=p.covers[0];
  if(!finishesFor(p).includes(s.finish))s.finish=finishesFor(p)[0];
  if(p.mount!=='surface')s.mounting='recessed';
  if(['kozus','larko'].includes(p.id))s.zone='drywall';else if(s.zone==='drywall')s.zone='under';
  if(t.type==='CCT')s.cct=Math.max(t.cctMin,Math.min(t.cctMax,s.cct));else s.cct=t.cct;
  if(s.detail==='curve'&&t.shape!=='s')s.detail='segment';
  if(['drywall','under','shelf','plinth'].includes(s.zone))s.zoneTrigger='manual';
  if(s.zone!=='cabinet'&&s.zonePosition==='shelf')s.zonePosition='front';
  if(t.encapsulation)s.sleeve='none';
  if(s.sleeve!=='none'&&(t.shape==='s'||t.width> sleeves.find(x=>x.id===s.sleeve).pcbMax))s.sleeve='none';
  if(['sleeve','seal'].includes(s.detail)&&s.sleeve==='none'&&!t.encapsulation)s.detail='segment';
  // Legacy room links and saved configurations reopen as a product study.
  return s;
}
export function specification(s) {
  const profile=profiles.find(x=>x.id===s.profile), strip=strips.find(x=>x.id===s.strip), cover=covers.find(x=>x.id===s.cover);
  const segments=Math.floor((s.length+1e-7)/strip.cut), stripLength=segments*strip.cut;
  const mode=strip.modes?.[s.powerMode||'high'],wattsPerMeter=mode?.watts??strip.watts,lumensPerMeter=mode?.lumens??strip.lumens,power=wattsPerMeter*stripLength/1000;
  const sleeve=sleeves.find(x=>x.id===s.sleeve)||null,envelope=sleeve|| (strip.encapsulation==='tube'?{width:strip.width+2,height:4}:strip.encapsulation==='coating'?{width:strip.envelopeWidth??strip.width,height:strip.envelopeHeight??5}:null);
  const envelopeFits=!envelope||(envelope.width<=profile.channel&&envelope.height<=(profile.channelDepth??(profile.height-profile.ledBase))-1);
  const fitVerified=(!sleeve||sleeve.verified)&&strip.envelopeVerified!==false;
  const availableHeight=Math.round(((profile.channelDepth??(profile.height-profile.ledBase))-1)*100)/100;
  const issues=[],issue=(code,message,severity='blocked')=>issues.push({code,message,severity});
  if(strip.width>profile.channel)issue('pcb-width',`PCB ${strip.width} mm przekracza kanał ${profile.channel} mm w ${profile.name}.`);
  if(sleeve&&(strip.width>sleeve.pcbMax||strip.shape==='s'||strip.encapsulation))issue('sleeve-pcb','Taśma nie jest zgodna z wybraną koszulką.');
  if(envelope&&envelope.width>profile.channel)issue('envelope-width',`Obrys ${envelope.width} mm jest szerszy niż kanał ${profile.channel} mm.`,fitVerified?'blocked':'pending');
  if(envelope&&envelope.height>availableHeight)issue('envelope-height',`Obrys ma ${envelope.height} mm wysokości; pod przesłoną pozostaje ok. ${availableHeight} mm.`,fitVerified?'blocked':'pending');
  if(!profile.covers.includes(cover.id))issue('cover-family',`${cover.name} nie jest przypisana do profilu ${profile.name}.`);
  if(cover.maxWatts&&wattsPerMeter>cover.maxWatts)issue('cover-power',`${cover.name}: maks. ${cover.maxWatts} W/m według KLUŚ. Taśma w tym wariancie ma ${wattsPerMeter} W/m; ściemniacz nie zmienia doboru.`);
  if(!finishesFor(profile).includes(s.finish))issue('finish','Brak tego wykończenia dla wybranego profilu w katalogu.');
  if(!fitVerified)issue('unverified-envelope','Gabaryt ochrony lub jej wnętrza wymaga potwierdzenia. Dopasowanie nie jest zatwierdzone.','pending');
  if(s.endcaps&&cover.capNote)issue('cover-endcap',cover.capNote,'pending');
  const fitStatus=issues.some(x=>x.severity==='blocked')?'blocked':issues.length?'pending':'compatible';
  const assemblyBlocked=issues.some(x=>['pcb-width','envelope-width','envelope-height','cover-family','sleeve-pcb'].includes(x.code));
  return {profile,strip,cover,sleeve,envelope,envelopeFits,fitVerified,availableHeight,issues,fitStatus,assemblyBlocked,finish:finishFor(profile,s.finish),cutVerified:strip.cutVerified!==false,stripLength,segments,offcut:s.length-stripLength,power,wattsPerMeter,lumensPerMeter,current:power/strip.voltage,terminals:strip.markings||['+'+strip.voltage+'V','−'],selectedTerminal:mode?.terminal, fits:strip.width<=profile.channel, coverFits:profile.covers.includes(cover.id),previewCct:strip.type==='CCT'?(s.cct<strip.cctMin||s.cct>strip.cctMax):s.cct!==strip.cct};
}
