import fs from 'node:fs/promises';
import {pages} from '../v2/catalogue-data.mjs';
const root = new URL('../',import.meta.url);
const originalLogo=await fs.readFile(new URL('wp-content/uploads/2025/12/PRESCOT_logo-podstawowe.svg',root),'utf8');
const logo=originalLogo.slice(originalLogo.indexOf('<svg')).replace(/<style>[\s\S]*?<\/style>/,'').replace('id="Warstwa_1"','aria-hidden="true"').replaceAll('class="st0"','class="v-wordmark-ink"').replaceAll('class="st1"','class="v-wordmark-accent"');
const escape = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const arrow = '<span aria-hidden="true">↗</span>';
const image = (src,alt,cls='',eager=false) => `<img class="${cls}" src="${src}" alt="${escape(alt)}" loading="${eager?'eager':'lazy'}" decoding="async">`;
const button = (href,label,cls='') => `<a class="v-button ${cls}" href="${href}">${label}${arrow}</a>`;
const header = p => `<a class="v-skip" href="v2/${p?p.slug+'/':''}#main">Przejdź do treści</a><header class="v-header"><a class="v-logo" href="./" aria-label="Prescot LED — strona główna">PRESCOT <span>LED</span></a><nav aria-label="Kategorie V2">${pages.map(x=>`<a href="v2/${x.slug}/" ${p?.slug===x.slug?'aria-current="page"':''}>${x.short}</a>`).join('')}</nav><a class="v-original" href="${p?.original||'oferta/'}">${p?.slug==='profile-led'?'Obecna oferta':'Obecna wersja'} ${arrow}</a></header>`;
const footer = `<footer class="v-footer"><a class="v-logo" href="./">PRESCOT <span>LED</span></a><p>Alternatywna prezentacja V2. Obecna strona pozostaje dostępna.</p><a href="v2/">Wszystkie wersje V2 ${arrow}</a></footer><nav class="v-mobile-nav" aria-label="Skróty mobilne"><a href="v2/">Kategorie V2</a><a href="kontakt/">Kontakt</a><a href="https://prescot.abstore.pl/">WAPRO B2B ${arrow}</a></nav>`;
const shell = (title,description,body,base='../../') => `<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><meta name="theme-color" content="#101316"><base href="${base}"><title>${escape(title)} · PRESCOT LED · V2</title><meta name="description" content="${escape(description)}"><link rel="stylesheet" href="v2/catalogue.css?v=20260911-v2-1"><script type="module" src="v2/catalogue.mjs?v=20260911-v2-1"></script></head><body>${body}</body></html>`;
const model = (m,i,p) => `<article class="v-model" id="model-${m.key}" data-model="${m.key}"><div class="v-model-visual ${m.photo?'is-photo':''}">${image(m.image,m.title,'v-main-image',i===0)}${m.detail?`<button class="v-gallery-toggle" data-primary="${m.image}" data-detail="${m.detail}" aria-label="Pokaż drugie zdjęcie: ${escape(m.title)}">Drugie zdjęcie <span aria-hidden="true">↔</span></button>`:''}<span class="v-model-index">${String(i+1).padStart(2,'0')} / ${String(p.models.length).padStart(2,'0')}</span></div><div class="v-model-copy"><p class="v-eyebrow">${p.slug==='profile-led'?'Zastosowanie':p.label}</p><h3>${m.title}</h3><p>${m.description}</p>${m.facts?`<dl>${m.facts.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl>`:''}<div class="v-model-actions">${button(`kontakt/?temat=${encodeURIComponent(m.title)}`,'Zapytaj o dobór')}${m.pdf?`<a class="v-text-link" href="${m.pdf}" target="_blank" rel="noopener">Karta PDF ↓</a>`:''}${m.video?`<button class="v-text-link" data-video="${m.video}" data-video-title="${m.title}">Zobacz film ▷</button>`:''}</div></div></article>`;
for(const p of pages) {
 for(const src of [p.hero,p.object,p.storyImage,...p.models.flatMap(m=>[m.image,m.detail,m.pdf,m.video])].filter(Boolean)) await fs.access(new URL(src,root));
 const body = `${header(p)}<main id="main"><section class="v-hero ${p.object?'':'v-hero-wide'}">${image(p.hero,p.heroAlt,'v-hero-photo',true)}<div class="v-hero-shade"></div><div class="v-hero-layout"><div class="v-hero-copy"><p class="v-eyebrow"><span class="v-pip"></span> ${p.label} <span class="v-version">V2</span></p><h1>${p.headline}</h1><p class="v-intro">${p.intro}</p><div class="v-actions">${button('#modele',p.slug==='profile-led'?'Zobacz zastosowania':'Poznaj kolekcję')}<a class="v-quiet-link" href="${p.original}">Porównaj z obecną wersją</a></div></div>${p.object?`<figure class="v-hero-object">${image(p.object,p.objectAlt,'',true)}<figcaption><span>${p.label}</span><span>PRESCOT LED ${arrow}</span></figcaption></figure>`:''}</div><div class="v-hero-bottom"><ul>${p.tags.map(t=>`<li>${t}</li>`).join('')}</ul><a href="#modele" aria-label="Przewiń do kolekcji">↓</a></div></section>
 <section class="v-collection v-section" id="modele"><div class="v-section-heading"><p class="v-eyebrow">${p.number} / ${p.slug==='profile-led'?'Zastosowania':'Kolekcja'}</p><h2>${p.section}</h2><p>${p.sectionIntro}</p></div><div class="v-model-nav" aria-label="${p.slug==='profile-led'?'Wybierz zastosowanie':'Wybierz model'}">${p.models.map((m,i)=>`<a id="tab-${m.key}" href="#model-${m.key}" data-model-select="${m.key}" ${i===0?'class="is-active"':''}>${m.label}</a>`).join('')}</div><div class="v-models">${p.models.map((m,i)=>model(m,i,p)).join('')}</div></section>
 <section class="v-story"><div class="v-story-image ${p.storyContain?'is-contained':''}">${image(p.storyImage,p.storyAlt)}</div><div class="v-story-copy"><p class="v-eyebrow">W Twojej instalacji</p><h2>${p.storyTitle}</h2><p>${p.story}</p>${button('kontakt/','Porozmawiajmy o projekcie','v-button-outline')}</div></section>
 <section class="v-section v-guide"><div class="v-section-heading"><p class="v-eyebrow">Przed wyborem</p><h2>Dobry efekt zaczyna się od doboru.</h2></div><div class="v-guide-grid">${p.guide.map(([title,text],i)=>`<article><span class="v-guide-number">0${i+1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>
 <section class="v-contact"><p class="v-eyebrow">PRESCOT LED</p><h2>Masz projekt?<br>Złóżmy go w całość.</h2><div class="v-actions">${button('kontakt/','Skontaktuj się z nami')}${button('https://prescot.abstore.pl/','Przejdź do WAPRO B2B','v-button-outline')}</div></section></main>${footer}<dialog class="v-video-dialog" aria-label="Film produktu"><header><h2>Film produktu</h2><button class="v-close-video" aria-label="Zamknij film">×</button></header><video controls playsinline preload="none"></video></dialog>`;
 const directory = new URL(`v2/${p.slug}/`,root);
 await fs.mkdir(directory,{recursive:true});
 const linkedBody=body.replaceAll('href="#modele"',`href="v2/${p.slug}/#modele"`).replaceAll('href="#model-',`href="v2/${p.slug}/#model-`);
 await fs.writeFile(new URL('index.html',directory),shell(p.label,p.intro,linkedBody));
}
await fs.writeFile(new URL('v2/index.html',root),shell('Cztery nowe spojrzenia na światło','Porównaj alternatywne prezentacje oferty Prescot LED.',`${header()}<main id="main" class="v-hub"><p class="v-eyebrow">PRESCOT / WERSJE DO PORÓWNANIA</p><h1>Cztery kategorie.<br>Nowa perspektywa.</h1><p>Wersje V2 na komputer i telefon. Obecne strony pozostają bez zastępowania.</p><div class="v-hub-grid">${pages.map(p=>`<a href="v2/${p.slug}/">${image(p.hero,p.heroAlt)}<div><span>${p.number} / V2</span><h2>${p.label} ${arrow}</h2></div></a>`).join('')}</div></main>${footer}`,'../'));
console.log('Built four V2 category pages and comparison hub. Originals unchanged.');
// Preserve the exact brand vector geometry in both light and dark headers.
for(const file of ['v2/index.html',...pages.map(p=>`v2/${p.slug}/index.html`)]){
 const url=new URL(file,root);let html=await fs.readFile(url,'utf8');
 html=html.replaceAll('PRESCOT <span>LED</span>',logo).replaceAll('<a class="v-logo" href="./">','<a class="v-logo" href="./" aria-label="Prescot LED — strona główna">');
 await fs.writeFile(url,html);
}
